<?php
/**
 * PromptRevision
 *
 * PHP version 8.1
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PromptJuggler
 *
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PromptJuggler\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use PromptJuggler\Client\ObjectSerializer;

/**
 * PromptRevision Class Doc Comment
 *
 * @description Prompt revision
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PromptRevision implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'PromptRevision';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'id' => 'string',
        'promptId' => 'string',
        'memory' => '\PromptJuggler\Client\Model\Memory',
        'provider' => '\PromptJuggler\Client\Model\Provider',
        'model' => '\PromptJuggler\Client\Model\Model',
        'modelParams' => '\PromptJuggler\Client\Model\ModelParams',
        'responseFormat' => '\PromptJuggler\Client\Model\ResponseFormat',
        'systemInstruction' => 'string',
        'messages' => '\PromptJuggler\Client\Model\ContentMessageResponse[]',
        'tools' => '\PromptJuggler\Client\Model\Tool[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'id' => 'uuid',
        'promptId' => 'uuid',
        'memory' => null,
        'provider' => null,
        'model' => null,
        'modelParams' => null,
        'responseFormat' => null,
        'systemInstruction' => null,
        'messages' => null,
        'tools' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'id' => false,
        'promptId' => false,
        'memory' => false,
        'provider' => false,
        'model' => false,
        'modelParams' => false,
        'responseFormat' => false,
        'systemInstruction' => true,
        'messages' => false,
        'tools' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'promptId' => 'promptId',
        'memory' => 'memory',
        'provider' => 'provider',
        'model' => 'model',
        'modelParams' => 'modelParams',
        'responseFormat' => 'responseFormat',
        'systemInstruction' => 'systemInstruction',
        'messages' => 'messages',
        'tools' => 'tools'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'promptId' => 'setPromptId',
        'memory' => 'setMemory',
        'provider' => 'setProvider',
        'model' => 'setModel',
        'modelParams' => 'setModelParams',
        'responseFormat' => 'setResponseFormat',
        'systemInstruction' => 'setSystemInstruction',
        'messages' => 'setMessages',
        'tools' => 'setTools'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'promptId' => 'getPromptId',
        'memory' => 'getMemory',
        'provider' => 'getProvider',
        'model' => 'getModel',
        'modelParams' => 'getModelParams',
        'responseFormat' => 'getResponseFormat',
        'systemInstruction' => 'getSystemInstruction',
        'messages' => 'getMessages',
        'tools' => 'getTools'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('promptId', $data ?? [], null);
        $this->setIfExists('memory', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('modelParams', $data ?? [], null);
        $this->setIfExists('responseFormat', $data ?? [], null);
        $this->setIfExists('systemInstruction', $data ?? [], null);
        $this->setIfExists('messages', $data ?? [], null);
        $this->setIfExists('tools', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['promptId'] === null) {
            $invalidProperties[] = "'promptId' can't be null";
        }
        if ($this->container['memory'] === null) {
            $invalidProperties[] = "'memory' can't be null";
        }
        if ($this->container['provider'] === null) {
            $invalidProperties[] = "'provider' can't be null";
        }
        if ($this->container['model'] === null) {
            $invalidProperties[] = "'model' can't be null";
        }
        if ($this->container['modelParams'] === null) {
            $invalidProperties[] = "'modelParams' can't be null";
        }
        if ($this->container['responseFormat'] === null) {
            $invalidProperties[] = "'responseFormat' can't be null";
        }
        if ($this->container['messages'] === null) {
            $invalidProperties[] = "'messages' can't be null";
        }
        if ($this->container['tools'] === null) {
            $invalidProperties[] = "'tools' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Prompt revision ID.
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets promptId
     *
     * @return string
     */
    public function getPromptId(): string
    {
        return $this->container['promptId'];
    }

    /**
     * Sets promptId
     *
     * @param string $promptId Prompt ID.
     *
     * @return $this
     */
    public function setPromptId(string $promptId): static
    {
        if (is_null($promptId)) {
            throw new InvalidArgumentException('non-nullable promptId cannot be null');
        }
        $this->container['promptId'] = $promptId;

        return $this;
    }

    /**
     * Gets memory
     *
     * @return \PromptJuggler\Client\Model\Memory
     */
    public function getMemory(): \PromptJuggler\Client\Model\Memory
    {
        return $this->container['memory'];
    }

    /**
     * Sets memory
     *
     * @param \PromptJuggler\Client\Model\Memory $memory Memory mode.
     *
     * @return $this
     */
    public function setMemory(\PromptJuggler\Client\Model\Memory $memory): static
    {
        if (is_null($memory)) {
            throw new InvalidArgumentException('non-nullable memory cannot be null');
        }
        $this->container['memory'] = $memory;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return \PromptJuggler\Client\Model\Provider
     */
    public function getProvider(): \PromptJuggler\Client\Model\Provider
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param \PromptJuggler\Client\Model\Provider $provider AI provider.
     *
     * @return $this
     */
    public function setProvider(\PromptJuggler\Client\Model\Provider $provider): static
    {
        if (is_null($provider)) {
            throw new InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets model
     *
     * @return \PromptJuggler\Client\Model\Model
     */
    public function getModel(): \PromptJuggler\Client\Model\Model
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param \PromptJuggler\Client\Model\Model $model AI model.
     *
     * @return $this
     */
    public function setModel(\PromptJuggler\Client\Model\Model $model): static
    {
        if (is_null($model)) {
            throw new InvalidArgumentException('non-nullable model cannot be null');
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets modelParams
     *
     * @return \PromptJuggler\Client\Model\ModelParams
     */
    public function getModelParams(): \PromptJuggler\Client\Model\ModelParams
    {
        return $this->container['modelParams'];
    }

    /**
     * Sets modelParams
     *
     * @param \PromptJuggler\Client\Model\ModelParams $modelParams Model parameters.
     *
     * @return $this
     */
    public function setModelParams(\PromptJuggler\Client\Model\ModelParams $modelParams): static
    {
        if (is_null($modelParams)) {
            throw new InvalidArgumentException('non-nullable modelParams cannot be null');
        }
        $this->container['modelParams'] = $modelParams;

        return $this;
    }

    /**
     * Gets responseFormat
     *
     * @return \PromptJuggler\Client\Model\ResponseFormat
     */
    public function getResponseFormat(): \PromptJuggler\Client\Model\ResponseFormat
    {
        return $this->container['responseFormat'];
    }

    /**
     * Sets responseFormat
     *
     * @param \PromptJuggler\Client\Model\ResponseFormat $responseFormat AI model response format.
     *
     * @return $this
     */
    public function setResponseFormat(\PromptJuggler\Client\Model\ResponseFormat $responseFormat): static
    {
        if (is_null($responseFormat)) {
            throw new InvalidArgumentException('non-nullable responseFormat cannot be null');
        }
        $this->container['responseFormat'] = $responseFormat;

        return $this;
    }

    /**
     * Gets systemInstruction
     *
     * @return string|null
     */
    public function getSystemInstruction(): ?string
    {
        return $this->container['systemInstruction'];
    }

    /**
     * Sets systemInstruction
     *
     * @param string|null $systemInstruction The system prompt.
     *
     * @return $this
     */
    public function setSystemInstruction(?string $systemInstruction): static
    {
        if (is_null($systemInstruction)) {
            array_push($this->openAPINullablesSetToNull, 'systemInstruction');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('systemInstruction', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['systemInstruction'] = $systemInstruction;

        return $this;
    }

    /**
     * Gets messages
     *
     * @return \PromptJuggler\Client\Model\ContentMessageResponse[]
     */
    public function getMessages(): array
    {
        return $this->container['messages'];
    }

    /**
     * Sets messages
     *
     * @param \PromptJuggler\Client\Model\ContentMessageResponse[] $messages User and assistant messages.
     *
     * @return $this
     */
    public function setMessages(array $messages): static
    {
        if (is_null($messages)) {
            throw new InvalidArgumentException('non-nullable messages cannot be null');
        }
        $this->container['messages'] = $messages;

        return $this;
    }

    /**
     * Gets tools
     *
     * @return \PromptJuggler\Client\Model\Tool[]
     */
    public function getTools(): array
    {
        return $this->container['tools'];
    }

    /**
     * Sets tools
     *
     * @param \PromptJuggler\Client\Model\Tool[] $tools Available tools.
     *
     * @return $this
     */
    public function setTools(array $tools): static
    {
        if (is_null($tools)) {
            throw new InvalidArgumentException('non-nullable tools cannot be null');
        }
        $this->container['tools'] = $tools;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


