<?php
/**
 * Tool
 *
 * PHP version 8.1
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PromptJuggler
 *
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PromptJuggler\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use PromptJuggler\Client\ObjectSerializer;

/**
 * Tool Class Doc Comment
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class Tool implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'Tool';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'type' => 'string',
        'allowedDomains' => 'string[]',
        'paramsSchema' => 'string',
        'url' => 'string',
        'method' => 'string',
        'headers' => '\PromptJuggler\Client\Model\HttpHeader[]',
        'name' => 'string',
        'description' => 'string',
        'failFast' => 'bool',
        'language' => 'string',
        'code' => 'string',
        'authorizationToken' => 'string',
        'allowedTools' => 'string[]',
        'versionRef' => '\PromptJuggler\Client\Model\VersionRef',
        'knowledgeBaseId' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'type' => null,
        'allowedDomains' => null,
        'paramsSchema' => null,
        'url' => null,
        'method' => null,
        'headers' => null,
        'name' => null,
        'description' => null,
        'failFast' => null,
        'language' => null,
        'code' => null,
        'authorizationToken' => null,
        'allowedTools' => null,
        'versionRef' => null,
        'knowledgeBaseId' => 'uuid'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'type' => false,
        'allowedDomains' => false,
        'paramsSchema' => false,
        'url' => false,
        'method' => false,
        'headers' => false,
        'name' => false,
        'description' => false,
        'failFast' => false,
        'language' => false,
        'code' => false,
        'authorizationToken' => false,
        'allowedTools' => false,
        'versionRef' => false,
        'knowledgeBaseId' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'type' => 'type',
        'allowedDomains' => 'allowedDomains',
        'paramsSchema' => 'paramsSchema',
        'url' => 'url',
        'method' => 'method',
        'headers' => 'headers',
        'name' => 'name',
        'description' => 'description',
        'failFast' => 'failFast',
        'language' => 'language',
        'code' => 'code',
        'authorizationToken' => 'authorizationToken',
        'allowedTools' => 'allowedTools',
        'versionRef' => 'versionRef',
        'knowledgeBaseId' => 'knowledgeBaseId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'type' => 'setType',
        'allowedDomains' => 'setAllowedDomains',
        'paramsSchema' => 'setParamsSchema',
        'url' => 'setUrl',
        'method' => 'setMethod',
        'headers' => 'setHeaders',
        'name' => 'setName',
        'description' => 'setDescription',
        'failFast' => 'setFailFast',
        'language' => 'setLanguage',
        'code' => 'setCode',
        'authorizationToken' => 'setAuthorizationToken',
        'allowedTools' => 'setAllowedTools',
        'versionRef' => 'setVersionRef',
        'knowledgeBaseId' => 'setKnowledgeBaseId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'type' => 'getType',
        'allowedDomains' => 'getAllowedDomains',
        'paramsSchema' => 'getParamsSchema',
        'url' => 'getUrl',
        'method' => 'getMethod',
        'headers' => 'getHeaders',
        'name' => 'getName',
        'description' => 'getDescription',
        'failFast' => 'getFailFast',
        'language' => 'getLanguage',
        'code' => 'getCode',
        'authorizationToken' => 'getAuthorizationToken',
        'allowedTools' => 'getAllowedTools',
        'versionRef' => 'getVersionRef',
        'knowledgeBaseId' => 'getKnowledgeBaseId'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const TYPE_HTTP = 'http';
    public const TYPE_KNOWLEDGE_SEARCH = 'knowledge_search';
    public const TYPE_MCP = 'mcp';
    public const TYPE_PROMPT = 'prompt';
    public const TYPE_SCRIPT = 'script';
    public const TYPE_WEB_SEARCH = 'web_search';
    public const TYPE_WORKFLOW = 'workflow';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getMethodAllowableValues()
    {
        return [
            self::TYPE_HTTP,
            self::TYPE_KNOWLEDGE_SEARCH,
            self::TYPE_MCP,
            self::TYPE_PROMPT,
            self::TYPE_SCRIPT,
            self::TYPE_WEB_SEARCH,
            self::TYPE_WORKFLOW,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getLanguageAllowableValues()
    {
        return [
            self::TYPE_HTTP,
            self::TYPE_KNOWLEDGE_SEARCH,
            self::TYPE_MCP,
            self::TYPE_PROMPT,
            self::TYPE_SCRIPT,
            self::TYPE_WEB_SEARCH,
            self::TYPE_WORKFLOW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;

        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('allowedDomains', $data ?? [], null);
        $this->setIfExists('paramsSchema', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('method', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], []);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('failFast', $data ?? [], false);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('authorizationToken', $data ?? [], null);
        $this->setIfExists('allowedTools', $data ?? [], null);
        $this->setIfExists('versionRef', $data ?? [], null);
        $this->setIfExists('knowledgeBaseId', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['paramsSchema'] === null) {
            $invalidProperties[] = "'paramsSchema' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['method'] === null) {
            $invalidProperties[] = "'method' can't be null";
        }
        $allowedValues = self::getMethodAllowableValues();
        if (!is_null($this->container['method']) && !in_array($this->container['method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'method', must be one of '%s'",
                $this->container['method'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if (!preg_match("/[a-zA-Z0-9_-]+/", $this->container['name'])) {
            $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /[a-zA-Z0-9_-]+/.";
        }

        if ($this->container['language'] === null) {
            $invalidProperties[] = "'language' can't be null";
        }
        $allowedValues = self::getLanguageAllowableValues();
        if (!is_null($this->container['language']) && !in_array($this->container['language'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'language', must be one of '%s'",
                $this->container['language'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['versionRef'] === null) {
            $invalidProperties[] = "'versionRef' can't be null";
        }
        if ($this->container['knowledgeBaseId'] === null) {
            $invalidProperties[] = "'knowledgeBaseId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType(): string
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType(string $type): static
    {
        if (is_null($type)) {
            throw new InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets allowedDomains
     *
     * @return string[]|null
     */
    public function getAllowedDomains(): ?array
    {
        return $this->container['allowedDomains'];
    }

    /**
     * Sets allowedDomains
     *
     * @param string[]|null $allowedDomains allowedDomains
     *
     * @return $this
     */
    public function setAllowedDomains(?array $allowedDomains): static
    {
        if (is_null($allowedDomains)) {
            throw new InvalidArgumentException('non-nullable allowedDomains cannot be null');
        }
        $this->container['allowedDomains'] = $allowedDomains;

        return $this;
    }

    /**
     * Gets paramsSchema
     *
     * @return string
     */
    public function getParamsSchema(): string
    {
        return $this->container['paramsSchema'];
    }

    /**
     * Sets paramsSchema
     *
     * @param string $paramsSchema JSON schema of the parameters this tool expects.
     *
     * @return $this
     */
    public function setParamsSchema(string $paramsSchema): static
    {
        if (is_null($paramsSchema)) {
            throw new InvalidArgumentException('non-nullable paramsSchema cannot be null');
        }
        $this->container['paramsSchema'] = $paramsSchema;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl(): string
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The URL of the MCP server.
     *
     * @return $this
     */
    public function setUrl(string $url): static
    {
        if (is_null($url)) {
            throw new InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets method
     *
     * @return string
     */
    public function getMethod(): string
    {
        return $this->container['method'];
    }

    /**
     * Sets method
     *
     * @param string $method method
     *
     * @return $this
     */
    public function setMethod(string $method): static
    {
        if (is_null($method)) {
            throw new InvalidArgumentException('non-nullable method cannot be null');
        }
        $allowedValues = self::getMethodAllowableValues();
        if (!in_array($method, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'method', must be one of '%s'",
                    $method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['method'] = $method;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return \PromptJuggler\Client\Model\HttpHeader[]|null
     */
    public function getHeaders(): ?array
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param \PromptJuggler\Client\Model\HttpHeader[]|null $headers The headers to send with the HTTP request. Can contain ${ENV_VAR} and {{inputName}} placeholders.
     *
     * @return $this
     */
    public function setHeaders(?array $headers): static
    {
        if (is_null($headers)) {
            throw new InvalidArgumentException('non-nullable headers cannot be null');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The tool’s name.
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((!preg_match("/[a-zA-Z0-9_-]+/", ObjectSerializer::toString($name)))) {
            throw new InvalidArgumentException("invalid value for \$name when calling Tool., must conform to the pattern /[a-zA-Z0-9_-]+/.");
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The tool’s description.
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets failFast
     *
     * @return bool|null
     */
    public function getFailFast(): ?bool
    {
        return $this->container['failFast'];
    }

    /**
     * Sets failFast
     *
     * @param bool|null $failFast Whether to stop processing if a tool call fails.
     *
     * @return $this
     */
    public function setFailFast(?bool $failFast): static
    {
        if (is_null($failFast)) {
            throw new InvalidArgumentException('non-nullable failFast cannot be null');
        }
        $this->container['failFast'] = $failFast;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string
     */
    public function getLanguage(): string
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string $language The language of the script to execute.
     *
     * @return $this
     */
    public function setLanguage(string $language): static
    {
        if (is_null($language)) {
            throw new InvalidArgumentException('non-nullable language cannot be null');
        }
        $allowedValues = self::getLanguageAllowableValues();
        if (!in_array($language, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'language', must be one of '%s'",
                    $language,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode(): string
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code The script that this tool executes.
     *
     * @return $this
     */
    public function setCode(string $code): static
    {
        if (is_null($code)) {
            throw new InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets authorizationToken
     *
     * @return string|null
     */
    public function getAuthorizationToken(): ?string
    {
        return $this->container['authorizationToken'];
    }

    /**
     * Sets authorizationToken
     *
     * @param string|null $authorizationToken Authorization token for the MCP server.
     *
     * @return $this
     */
    public function setAuthorizationToken(?string $authorizationToken): static
    {
        if (is_null($authorizationToken)) {
            throw new InvalidArgumentException('non-nullable authorizationToken cannot be null');
        }
        $this->container['authorizationToken'] = $authorizationToken;

        return $this;
    }

    /**
     * Gets allowedTools
     *
     * @return string[]|null
     */
    public function getAllowedTools(): ?array
    {
        return $this->container['allowedTools'];
    }

    /**
     * Sets allowedTools
     *
     * @param string[]|null $allowedTools Tool names the model may call. Empty or omitted allows all of the server’s tools.
     *
     * @return $this
     */
    public function setAllowedTools(?array $allowedTools): static
    {
        if (is_null($allowedTools)) {
            throw new InvalidArgumentException('non-nullable allowedTools cannot be null');
        }
        $this->container['allowedTools'] = $allowedTools;

        return $this;
    }

    /**
     * Gets versionRef
     *
     * @return \PromptJuggler\Client\Model\VersionRef
     */
    public function getVersionRef(): \PromptJuggler\Client\Model\VersionRef
    {
        return $this->container['versionRef'];
    }

    /**
     * Sets versionRef
     *
     * @param \PromptJuggler\Client\Model\VersionRef $versionRef Referencing the workflow revision either by id or version number or tag.
     *
     * @return $this
     */
    public function setVersionRef(\PromptJuggler\Client\Model\VersionRef $versionRef): static
    {
        if (is_null($versionRef)) {
            throw new InvalidArgumentException('non-nullable versionRef cannot be null');
        }
        $this->container['versionRef'] = $versionRef;

        return $this;
    }

    /**
     * Gets knowledgeBaseId
     *
     * @return string
     */
    public function getKnowledgeBaseId(): string
    {
        return $this->container['knowledgeBaseId'];
    }

    /**
     * Sets knowledgeBaseId
     *
     * @param string $knowledgeBaseId knowledgeBaseId
     *
     * @return $this
     */
    public function setKnowledgeBaseId(string $knowledgeBaseId): static
    {
        if (is_null($knowledgeBaseId)) {
            throw new InvalidArgumentException('non-nullable knowledgeBaseId cannot be null');
        }
        $this->container['knowledgeBaseId'] = $knowledgeBaseId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


