<?php
/**
 * Model
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PromptJuggler
 *
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Model Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Model
{
    /**
     * Possible values of this enum
     */
    public const GPT_5_5 = 'gpt-5.5';

    public const GPT_5_5_PRO = 'gpt-5.5-pro';

    public const GPT_5_4 = 'gpt-5.4';

    public const GPT_5_4_MINI = 'gpt-5.4-mini';

    public const GPT_5_4_NANO = 'gpt-5.4-nano';

    public const GPT_5_4_PRO = 'gpt-5.4-pro';

    public const GPT_5_2 = 'gpt-5.2';

    public const GPT_5_2_PRO = 'gpt-5.2-pro';

    public const GPT_5_1 = 'gpt-5.1';

    public const GPT_4_1 = 'gpt-4.1';

    public const GPT_4_1_MINI = 'gpt-4.1-mini';

    public const O1_MINI = 'o1-mini';

    public const GPT_4O = 'gpt-4o';

    public const GPT_4O_MINI = 'gpt-4o-mini';

    public const GEMINI_3_1_PRO_PREVIEW = 'gemini-3.1-pro-preview';

    public const GEMINI_3_FLASH_PREVIEW = 'gemini-3-flash-preview';

    public const GEMINI_2_5_PRO = 'gemini-2.5-pro';

    public const GEMINI_2_5_FLASH = 'gemini-2.5-flash';

    public const GEMINI_2_5_FLASH_LITE = 'gemini-2.5-flash-lite';

    public const GEMINI_2_0_FLASH = 'gemini-2.0-flash';

    public const GEMINI_2_0_FLASH_LITE = 'gemini-2.0-flash-lite';

    public const CLAUDE_OPUS_4_8 = 'claude-opus-4-8';

    public const CLAUDE_OPUS_4_7 = 'claude-opus-4-7';

    public const CLAUDE_OPUS_4_6 = 'claude-opus-4-6';

    public const CLAUDE_OPUS_4_5 = 'claude-opus-4-5';

    public const CLAUDE_SONNET_4_6 = 'claude-sonnet-4-6';

    public const CLAUDE_SONNET_4_5 = 'claude-sonnet-4-5';

    public const CLAUDE_HAIKU_4_5 = 'claude-haiku-4-5';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GPT_5_5,
            self::GPT_5_5_PRO,
            self::GPT_5_4,
            self::GPT_5_4_MINI,
            self::GPT_5_4_NANO,
            self::GPT_5_4_PRO,
            self::GPT_5_2,
            self::GPT_5_2_PRO,
            self::GPT_5_1,
            self::GPT_4_1,
            self::GPT_4_1_MINI,
            self::O1_MINI,
            self::GPT_4O,
            self::GPT_4O_MINI,
            self::GEMINI_3_1_PRO_PREVIEW,
            self::GEMINI_3_FLASH_PREVIEW,
            self::GEMINI_2_5_PRO,
            self::GEMINI_2_5_FLASH,
            self::GEMINI_2_5_FLASH_LITE,
            self::GEMINI_2_0_FLASH,
            self::GEMINI_2_0_FLASH_LITE,
            self::CLAUDE_OPUS_4_8,
            self::CLAUDE_OPUS_4_7,
            self::CLAUDE_OPUS_4_6,
            self::CLAUDE_OPUS_4_5,
            self::CLAUDE_SONNET_4_6,
            self::CLAUDE_SONNET_4_5,
            self::CLAUDE_HAIKU_4_5
        ];
    }
}


