<?php
/**
 * ModelParams
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PromptJuggler
 *
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ModelParams Class Doc Comment
 *
 * @category Class
 * @description AI model parameters.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelParams implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ModelParams';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'maxCompletionTokens' => 'int',
        'temperature' => 'float',
        'topP' => 'float',
        'verbosity' => 'string',
        'reasoningEffort' => 'string',
        'reasoningSummary' => 'bool',
        'serviceTier' => '\OpenAPI\Client\Model\ServiceTier'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'maxCompletionTokens' => null,
        'temperature' => 'float',
        'topP' => 'float',
        'verbosity' => null,
        'reasoningEffort' => null,
        'reasoningSummary' => null,
        'serviceTier' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'maxCompletionTokens' => true,
        'temperature' => true,
        'topP' => true,
        'verbosity' => true,
        'reasoningEffort' => true,
        'reasoningSummary' => true,
        'serviceTier' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'maxCompletionTokens' => 'maxCompletionTokens',
        'temperature' => 'temperature',
        'topP' => 'topP',
        'verbosity' => 'verbosity',
        'reasoningEffort' => 'reasoningEffort',
        'reasoningSummary' => 'reasoningSummary',
        'serviceTier' => 'serviceTier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'maxCompletionTokens' => 'setMaxCompletionTokens',
        'temperature' => 'setTemperature',
        'topP' => 'setTopP',
        'verbosity' => 'setVerbosity',
        'reasoningEffort' => 'setReasoningEffort',
        'reasoningSummary' => 'setReasoningSummary',
        'serviceTier' => 'setServiceTier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'maxCompletionTokens' => 'getMaxCompletionTokens',
        'temperature' => 'getTemperature',
        'topP' => 'getTopP',
        'verbosity' => 'getVerbosity',
        'reasoningEffort' => 'getReasoningEffort',
        'reasoningSummary' => 'getReasoningSummary',
        'serviceTier' => 'getServiceTier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const VERBOSITY_LOW = 'low';
    public const VERBOSITY_MEDIUM = 'medium';
    public const VERBOSITY_HIGH = 'high';
    public const REASONING_EFFORT_NONE = 'none';
    public const REASONING_EFFORT_MINIMAL = 'minimal';
    public const REASONING_EFFORT_LOW = 'low';
    public const REASONING_EFFORT_MEDIUM = 'medium';
    public const REASONING_EFFORT_HIGH = 'high';
    public const REASONING_EFFORT_XHIGH = 'xhigh';
    public const REASONING_EFFORT_MAX = 'max';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVerbosityAllowableValues()
    {
        return [
            self::VERBOSITY_LOW,
            self::VERBOSITY_MEDIUM,
            self::VERBOSITY_HIGH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReasoningEffortAllowableValues()
    {
        return [
            self::REASONING_EFFORT_NONE,
            self::REASONING_EFFORT_MINIMAL,
            self::REASONING_EFFORT_LOW,
            self::REASONING_EFFORT_MEDIUM,
            self::REASONING_EFFORT_HIGH,
            self::REASONING_EFFORT_XHIGH,
            self::REASONING_EFFORT_MAX,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('maxCompletionTokens', $data ?? [], null);
        $this->setIfExists('temperature', $data ?? [], null);
        $this->setIfExists('topP', $data ?? [], null);
        $this->setIfExists('verbosity', $data ?? [], null);
        $this->setIfExists('reasoningEffort', $data ?? [], null);
        $this->setIfExists('reasoningSummary', $data ?? [], null);
        $this->setIfExists('serviceTier', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['maxCompletionTokens']) && ($this->container['maxCompletionTokens'] < 1)) {
            $invalidProperties[] = "invalid value for 'maxCompletionTokens', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['temperature']) && ($this->container['temperature'] > 2)) {
            $invalidProperties[] = "invalid value for 'temperature', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['temperature']) && ($this->container['temperature'] < 0)) {
            $invalidProperties[] = "invalid value for 'temperature', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['topP']) && ($this->container['topP'] > 2)) {
            $invalidProperties[] = "invalid value for 'topP', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['topP']) && ($this->container['topP'] < 0)) {
            $invalidProperties[] = "invalid value for 'topP', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getVerbosityAllowableValues();
        if (!is_null($this->container['verbosity']) && !in_array($this->container['verbosity'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'verbosity', must be one of '%s'",
                $this->container['verbosity'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getReasoningEffortAllowableValues();
        if (!is_null($this->container['reasoningEffort']) && !in_array($this->container['reasoningEffort'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reasoningEffort', must be one of '%s'",
                $this->container['reasoningEffort'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets maxCompletionTokens
     *
     * @return int|null
     */
    public function getMaxCompletionTokens()
    {
        return $this->container['maxCompletionTokens'];
    }

    /**
     * Sets maxCompletionTokens
     *
     * @param int|null $maxCompletionTokens Maximum completion tokens.
     *
     * @return self
     */
    public function setMaxCompletionTokens($maxCompletionTokens)
    {
        if (is_null($maxCompletionTokens)) {
            array_push($this->openAPINullablesSetToNull, 'maxCompletionTokens');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maxCompletionTokens', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maxCompletionTokens) && ($maxCompletionTokens < 1)) {
            throw new \InvalidArgumentException('invalid value for $maxCompletionTokens when calling ModelParams., must be bigger than or equal to 1.');
        }

        $this->container['maxCompletionTokens'] = $maxCompletionTokens;

        return $this;
    }

    /**
     * Gets temperature
     *
     * @return float|null
     */
    public function getTemperature()
    {
        return $this->container['temperature'];
    }

    /**
     * Sets temperature
     *
     * @param float|null $temperature Temperature.
     *
     * @return self
     */
    public function setTemperature($temperature)
    {
        if (is_null($temperature)) {
            array_push($this->openAPINullablesSetToNull, 'temperature');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('temperature', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($temperature) && ($temperature > 2)) {
            throw new \InvalidArgumentException('invalid value for $temperature when calling ModelParams., must be smaller than or equal to 2.');
        }
        if (!is_null($temperature) && ($temperature < 0)) {
            throw new \InvalidArgumentException('invalid value for $temperature when calling ModelParams., must be bigger than or equal to 0.');
        }

        $this->container['temperature'] = $temperature;

        return $this;
    }

    /**
     * Gets topP
     *
     * @return float|null
     */
    public function getTopP()
    {
        return $this->container['topP'];
    }

    /**
     * Sets topP
     *
     * @param float|null $topP Top P.
     *
     * @return self
     */
    public function setTopP($topP)
    {
        if (is_null($topP)) {
            array_push($this->openAPINullablesSetToNull, 'topP');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('topP', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($topP) && ($topP > 2)) {
            throw new \InvalidArgumentException('invalid value for $topP when calling ModelParams., must be smaller than or equal to 2.');
        }
        if (!is_null($topP) && ($topP < 0)) {
            throw new \InvalidArgumentException('invalid value for $topP when calling ModelParams., must be bigger than or equal to 0.');
        }

        $this->container['topP'] = $topP;

        return $this;
    }

    /**
     * Gets verbosity
     *
     * @return string|null
     */
    public function getVerbosity()
    {
        return $this->container['verbosity'];
    }

    /**
     * Sets verbosity
     *
     * @param string|null $verbosity Verbosity.
     *
     * @return self
     */
    public function setVerbosity($verbosity)
    {
        if (is_null($verbosity)) {
            array_push($this->openAPINullablesSetToNull, 'verbosity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('verbosity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getVerbosityAllowableValues();
        if (!is_null($verbosity) && !in_array($verbosity, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'verbosity', must be one of '%s'",
                    $verbosity,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['verbosity'] = $verbosity;

        return $this;
    }

    /**
     * Gets reasoningEffort
     *
     * @return string|null
     */
    public function getReasoningEffort()
    {
        return $this->container['reasoningEffort'];
    }

    /**
     * Sets reasoningEffort
     *
     * @param string|null $reasoningEffort Reasoning effort.
     *
     * @return self
     */
    public function setReasoningEffort($reasoningEffort)
    {
        if (is_null($reasoningEffort)) {
            array_push($this->openAPINullablesSetToNull, 'reasoningEffort');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reasoningEffort', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getReasoningEffortAllowableValues();
        if (!is_null($reasoningEffort) && !in_array($reasoningEffort, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'reasoningEffort', must be one of '%s'",
                    $reasoningEffort,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['reasoningEffort'] = $reasoningEffort;

        return $this;
    }

    /**
     * Gets reasoningSummary
     *
     * @return bool|null
     */
    public function getReasoningSummary()
    {
        return $this->container['reasoningSummary'];
    }

    /**
     * Sets reasoningSummary
     *
     * @param bool|null $reasoningSummary Return reasoning summary.
     *
     * @return self
     */
    public function setReasoningSummary($reasoningSummary)
    {
        if (is_null($reasoningSummary)) {
            array_push($this->openAPINullablesSetToNull, 'reasoningSummary');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reasoningSummary', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reasoningSummary'] = $reasoningSummary;

        return $this;
    }

    /**
     * Gets serviceTier
     *
     * @return \OpenAPI\Client\Model\ServiceTier|null
     */
    public function getServiceTier()
    {
        return $this->container['serviceTier'];
    }

    /**
     * Sets serviceTier
     *
     * @param \OpenAPI\Client\Model\ServiceTier|null $serviceTier Service tier.
     *
     * @return self
     */
    public function setServiceTier($serviceTier)
    {
        if (is_null($serviceTier)) {
            array_push($this->openAPINullablesSetToNull, 'serviceTier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('serviceTier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['serviceTier'] = $serviceTier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


