<?php
/**
 * KnowledgeBasesApi
 * PHP version 8.1
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PromptJuggler
 *
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PromptJuggler\Client\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use PromptJuggler\Client\ApiException;
use PromptJuggler\Client\Configuration;
use PromptJuggler\Client\HeaderSelector;
use PromptJuggler\Client\FormDataProcessor;
use PromptJuggler\Client\ObjectSerializer;

/**
 * KnowledgeBasesApi Class Doc Comment
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KnowledgeBasesApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'publicDeleteDocument' => [
            'application/json',
        ],
        'publicGetDocument' => [
            'application/json',
        ],
        'publicGetKnowledgeBase' => [
            'application/json',
        ],
        'publicUploadDocuments' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation publicDeleteDocument
     *
     * Delete a knowledge document
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicDeleteDocument'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \PromptJuggler\Client\Model\ErrorResponse|null
     */
    public function publicDeleteDocument(
        string $id,
        string $contentType = self::contentTypes['publicDeleteDocument'][0]
    ): ?\PromptJuggler\Client\Model\ErrorResponse
    {
        list($response) = $this->publicDeleteDocumentWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation publicDeleteDocumentWithHttpInfo
     *
     * Delete a knowledge document
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicDeleteDocument'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function publicDeleteDocumentWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['publicDeleteDocument'][0]
    ): array
    {
        $request = $this->publicDeleteDocumentRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation publicDeleteDocumentAsync
     *
     * Delete a knowledge document
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicDeleteDocument'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicDeleteDocumentAsync(
        string $id,
        string $contentType = self::contentTypes['publicDeleteDocument'][0]
    ): PromiseInterface
    {
        return $this->publicDeleteDocumentAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation publicDeleteDocumentAsyncWithHttpInfo
     *
     * Delete a knowledge document
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicDeleteDocument'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicDeleteDocumentAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['publicDeleteDocument'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->publicDeleteDocumentRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'publicDeleteDocument'
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicDeleteDocument'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function publicDeleteDocumentRequest(
        string $id,
        string $contentType = self::contentTypes['publicDeleteDocument'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling publicDeleteDocument'
            );
        }


        $resourcePath = '/api/v1/knowledge-documents/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation publicGetDocument
     *
     * Get a knowledge document by ID
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetDocument'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \PromptJuggler\Client\Model\KnowledgeDocumentResponse|\PromptJuggler\Client\Model\ErrorResponse|null
     */
    public function publicGetDocument(
        string $id,
        string $contentType = self::contentTypes['publicGetDocument'][0]
    ): \PromptJuggler\Client\Model\KnowledgeDocumentResponse|\PromptJuggler\Client\Model\ErrorResponse|null
    {
        list($response) = $this->publicGetDocumentWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation publicGetDocumentWithHttpInfo
     *
     * Get a knowledge document by ID
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetDocument'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \PromptJuggler\Client\Model\KnowledgeDocumentResponse|\PromptJuggler\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function publicGetDocumentWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['publicGetDocument'][0]
    ): array
    {
        $request = $this->publicGetDocumentRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\KnowledgeDocumentResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PromptJuggler\Client\Model\KnowledgeDocumentResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\KnowledgeDocumentResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation publicGetDocumentAsync
     *
     * Get a knowledge document by ID
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetDocument'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicGetDocumentAsync(
        string $id,
        string $contentType = self::contentTypes['publicGetDocument'][0]
    ): PromiseInterface
    {
        return $this->publicGetDocumentAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation publicGetDocumentAsyncWithHttpInfo
     *
     * Get a knowledge document by ID
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetDocument'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicGetDocumentAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['publicGetDocument'][0]
    ): PromiseInterface
    {
        $returnType = '\PromptJuggler\Client\Model\KnowledgeDocumentResponse';
        $request = $this->publicGetDocumentRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'publicGetDocument'
     *
     * @param  string $id Document ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetDocument'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function publicGetDocumentRequest(
        string $id,
        string $contentType = self::contentTypes['publicGetDocument'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling publicGetDocument'
            );
        }


        $resourcePath = '/api/v1/knowledge-documents/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation publicGetKnowledgeBase
     *
     * Get a knowledge base by slug
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetKnowledgeBase'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \PromptJuggler\Client\Model\KnowledgeBaseResponse|\PromptJuggler\Client\Model\ErrorResponse|null
     */
    public function publicGetKnowledgeBase(
        string $slug,
        string $contentType = self::contentTypes['publicGetKnowledgeBase'][0]
    ): \PromptJuggler\Client\Model\KnowledgeBaseResponse|\PromptJuggler\Client\Model\ErrorResponse|null
    {
        list($response) = $this->publicGetKnowledgeBaseWithHttpInfo($slug, $contentType);
        return $response;
    }

    /**
     * Operation publicGetKnowledgeBaseWithHttpInfo
     *
     * Get a knowledge base by slug
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetKnowledgeBase'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \PromptJuggler\Client\Model\KnowledgeBaseResponse|\PromptJuggler\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function publicGetKnowledgeBaseWithHttpInfo(
        string $slug,
        string $contentType = self::contentTypes['publicGetKnowledgeBase'][0]
    ): array
    {
        $request = $this->publicGetKnowledgeBaseRequest($slug, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\KnowledgeBaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PromptJuggler\Client\Model\KnowledgeBaseResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\KnowledgeBaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation publicGetKnowledgeBaseAsync
     *
     * Get a knowledge base by slug
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetKnowledgeBase'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicGetKnowledgeBaseAsync(
        string $slug,
        string $contentType = self::contentTypes['publicGetKnowledgeBase'][0]
    ): PromiseInterface
    {
        return $this->publicGetKnowledgeBaseAsyncWithHttpInfo($slug, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation publicGetKnowledgeBaseAsyncWithHttpInfo
     *
     * Get a knowledge base by slug
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetKnowledgeBase'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicGetKnowledgeBaseAsyncWithHttpInfo(
        string $slug,
        string $contentType = self::contentTypes['publicGetKnowledgeBase'][0]
    ): PromiseInterface
    {
        $returnType = '\PromptJuggler\Client\Model\KnowledgeBaseResponse';
        $request = $this->publicGetKnowledgeBaseRequest($slug, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'publicGetKnowledgeBase'
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicGetKnowledgeBase'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function publicGetKnowledgeBaseRequest(
        string $slug,
        string $contentType = self::contentTypes['publicGetKnowledgeBase'][0]
    ): Request
    {

        // verify the required parameter 'slug' is set
        if ($slug === null || (is_array($slug) && count($slug) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $slug when calling publicGetKnowledgeBase'
            );
        }


        $resourcePath = '/api/v1/knowledge-bases/{slug}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($slug !== null) {
            $resourcePath = str_replace(
                '{slug}',
                ObjectSerializer::toPathValue($slug),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation publicUploadDocuments
     *
     * Upload documents to a knowledge base
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  \SplFileObject[]|null $files files (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicUploadDocuments'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \PromptJuggler\Client\Model\KnowledgeDocumentResponse[]|\PromptJuggler\Client\Model\ErrorResponse|null
     */
    public function publicUploadDocuments(
        string $slug,
        ?array $files = null,
        string $contentType = self::contentTypes['publicUploadDocuments'][0]
    ): array|\PromptJuggler\Client\Model\ErrorResponse|null
    {
        list($response) = $this->publicUploadDocumentsWithHttpInfo($slug, $files, $contentType);
        return $response;
    }

    /**
     * Operation publicUploadDocumentsWithHttpInfo
     *
     * Upload documents to a knowledge base
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  \SplFileObject[]|null $files (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicUploadDocuments'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \PromptJuggler\Client\Model\KnowledgeDocumentResponse[]|\PromptJuggler\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function publicUploadDocumentsWithHttpInfo(
        string $slug,
        ?array $files = null,
        string $contentType = self::contentTypes['publicUploadDocuments'][0]
    ): array
    {
        $request = $this->publicUploadDocumentsRequest($slug, $files, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\KnowledgeDocumentResponse[]',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PromptJuggler\Client\Model\KnowledgeDocumentResponse[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\KnowledgeDocumentResponse[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation publicUploadDocumentsAsync
     *
     * Upload documents to a knowledge base
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  \SplFileObject[]|null $files (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicUploadDocuments'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicUploadDocumentsAsync(
        string $slug,
        ?array $files = null,
        string $contentType = self::contentTypes['publicUploadDocuments'][0]
    ): PromiseInterface
    {
        return $this->publicUploadDocumentsAsyncWithHttpInfo($slug, $files, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation publicUploadDocumentsAsyncWithHttpInfo
     *
     * Upload documents to a knowledge base
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  \SplFileObject[]|null $files (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicUploadDocuments'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function publicUploadDocumentsAsyncWithHttpInfo(
        string $slug,
        ?array $files = null,
        string $contentType = self::contentTypes['publicUploadDocuments'][0]
    ): PromiseInterface
    {
        $returnType = '\PromptJuggler\Client\Model\KnowledgeDocumentResponse[]';
        $request = $this->publicUploadDocumentsRequest($slug, $files, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'publicUploadDocuments'
     *
     * @param  string $slug Knowledge base handle (required)
     * @param  \SplFileObject[]|null $files (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['publicUploadDocuments'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function publicUploadDocumentsRequest(
        string $slug,
        ?array $files = null,
        string $contentType = self::contentTypes['publicUploadDocuments'][0]
    ): Request
    {

        // verify the required parameter 'slug' is set
        if ($slug === null || (is_array($slug) && count($slug) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $slug when calling publicUploadDocuments'
            );
        }



        $resourcePath = '/api/v1/knowledge-bases/{slug}/documents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($slug !== null) {
            $resourcePath = str_replace(
                '{slug}',
                ObjectSerializer::toPathValue($slug),
                $resourcePath
            );
        }

        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'files' => $files,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
