<?php
/**
 * PromptRunsApi
 * PHP version 8.1
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PromptJuggler
 *
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PromptJuggler\Client\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use PromptJuggler\Client\ApiException;
use PromptJuggler\Client\Configuration;
use PromptJuggler\Client\HeaderSelector;
use PromptJuggler\Client\FormDataProcessor;
use PromptJuggler\Client\ObjectSerializer;

/**
 * PromptRunsApi Class Doc Comment
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PromptRunsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createPromptRun' => [
            'application/json',
        ],
        'getPromptRun' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation createPromptRun
     *
     * Create and trigger a prompt run
     *
     * @param  string $slug Prompt Handle (required)
     * @param  \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version Specific version or tag or id (required)
     * @param  \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun CreatePromptRun (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPromptRun'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \PromptJuggler\Client\Model\CreatePromptRunResponse|\PromptJuggler\Client\Model\ErrorResponse|null
     */
    public function createPromptRun(
        string $slug,
        \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version,
        \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun,
        string $contentType = self::contentTypes['createPromptRun'][0]
    ): \PromptJuggler\Client\Model\CreatePromptRunResponse|\PromptJuggler\Client\Model\ErrorResponse|null
    {
        list($response) = $this->createPromptRunWithHttpInfo($slug, $version, $CreatePromptRun, $contentType);
        return $response;
    }

    /**
     * Operation createPromptRunWithHttpInfo
     *
     * Create and trigger a prompt run
     *
     * @param  string $slug Prompt Handle (required)
     * @param  \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version Specific version or tag or id (required)
     * @param  \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPromptRun'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \PromptJuggler\Client\Model\CreatePromptRunResponse|\PromptJuggler\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createPromptRunWithHttpInfo(
        string $slug,
        \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version,
        \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun,
        string $contentType = self::contentTypes['createPromptRun'][0]
    ): array
    {
        $request = $this->createPromptRunRequest($slug, $version, $CreatePromptRun, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\CreatePromptRunResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PromptJuggler\Client\Model\CreatePromptRunResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\CreatePromptRunResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation createPromptRunAsync
     *
     * Create and trigger a prompt run
     *
     * @param  string $slug Prompt Handle (required)
     * @param  \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version Specific version or tag or id (required)
     * @param  \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPromptRun'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createPromptRunAsync(
        string $slug,
        \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version,
        \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun,
        string $contentType = self::contentTypes['createPromptRun'][0]
    ): PromiseInterface
    {
        return $this->createPromptRunAsyncWithHttpInfo($slug, $version, $CreatePromptRun, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createPromptRunAsyncWithHttpInfo
     *
     * Create and trigger a prompt run
     *
     * @param  string $slug Prompt Handle (required)
     * @param  \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version Specific version or tag or id (required)
     * @param  \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPromptRun'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createPromptRunAsyncWithHttpInfo(
        string $slug,
        \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version,
        \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun,
        string $contentType = self::contentTypes['createPromptRun'][0]
    ): PromiseInterface
    {
        $returnType = '\PromptJuggler\Client\Model\CreatePromptRunResponse';
        $request = $this->createPromptRunRequest($slug, $version, $CreatePromptRun, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createPromptRun'
     *
     * @param  string $slug Prompt Handle (required)
     * @param  \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version Specific version or tag or id (required)
     * @param  \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPromptRun'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createPromptRunRequest(
        string $slug,
        \PromptJuggler\Client\Model\GetPromptRevisionVersionParameter $version,
        \PromptJuggler\Client\Model\CreatePromptRun $CreatePromptRun,
        string $contentType = self::contentTypes['createPromptRun'][0]
    ): Request
    {

        // verify the required parameter 'slug' is set
        if ($slug === null || (is_array($slug) && count($slug) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $slug when calling createPromptRun'
            );
        }

        // verify the required parameter 'version' is set
        if ($version === null || (is_array($version) && count($version) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $version when calling createPromptRun'
            );
        }

        // verify the required parameter 'CreatePromptRun' is set
        if ($CreatePromptRun === null || (is_array($CreatePromptRun) && count($CreatePromptRun) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $CreatePromptRun when calling createPromptRun'
            );
        }


        $resourcePath = '/api/v1/prompts/{slug}/{version}/runs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($slug !== null) {
            $resourcePath = str_replace(
                '{slug}',
                ObjectSerializer::toPathValue($slug),
                $resourcePath
            );
        }
        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{version}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($CreatePromptRun)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($CreatePromptRun));
            } else {
                $httpBody = $CreatePromptRun;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPromptRun
     *
     * Get a prompt run by ID
     *
     * @param  string $id Prompt run ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPromptRun'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \PromptJuggler\Client\Model\PromptRun|\PromptJuggler\Client\Model\ErrorResponse|null
     */
    public function getPromptRun(
        string $id,
        string $contentType = self::contentTypes['getPromptRun'][0]
    ): \PromptJuggler\Client\Model\PromptRun|\PromptJuggler\Client\Model\ErrorResponse|null
    {
        list($response) = $this->getPromptRunWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getPromptRunWithHttpInfo
     *
     * Get a prompt run by ID
     *
     * @param  string $id Prompt run ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPromptRun'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \PromptJuggler\Client\Model\PromptRun|\PromptJuggler\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPromptRunWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['getPromptRun'][0]
    ): array
    {
        $request = $this->getPromptRunRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\PromptRun',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PromptJuggler\Client\Model\PromptRun',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\PromptRun',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PromptJuggler\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getPromptRunAsync
     *
     * Get a prompt run by ID
     *
     * @param  string $id Prompt run ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPromptRun'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getPromptRunAsync(
        string $id,
        string $contentType = self::contentTypes['getPromptRun'][0]
    ): PromiseInterface
    {
        return $this->getPromptRunAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPromptRunAsyncWithHttpInfo
     *
     * Get a prompt run by ID
     *
     * @param  string $id Prompt run ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPromptRun'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getPromptRunAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['getPromptRun'][0]
    ): PromiseInterface
    {
        $returnType = '\PromptJuggler\Client\Model\PromptRun';
        $request = $this->getPromptRunRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPromptRun'
     *
     * @param  string $id Prompt run ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPromptRun'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPromptRunRequest(
        string $id,
        string $contentType = self::contentTypes['getPromptRun'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling getPromptRun'
            );
        }


        $resourcePath = '/api/v1/promptruns/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
