<?php
/**
 * MemoryTest
 *
 * PHP version 8.1
 *
 * @package  PromptJuggler\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PromptJuggler
 *
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PromptJuggler\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MemoryTest Class Doc Comment
 *
 * @description Memory
 * @package     PromptJuggler\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MemoryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Memory"
     */
    public function testMemory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
